version: '3.8'

services:
  app:
    build: .
    container_name: policy_assistant
    ports:
      - "2200:2200"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=flask_app.py
    volumes:
      - .:/app
    #command: flask run --host=0.0.0.0 --port=2200
    command: ["python3", "flask_app.py"]